networks:
    #samm-network:
    #    driver: bridge
    frontend:
        external: true

services:
    nextjs:
        build:
            context: .
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        networks:
        #    - samm-network
            - frontend
        ports:
            - "3001:3000"



